# Generated by Django 6.0.1 on 2026-01-13 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns_selected', models.JSONField(help_text='List of column names that were kept')),
                ('columns_removed', models.JSONField(help_text='List of column names that were removed')),
                ('output_csv_path', models.FileField(upload_to='outputs/%Y/%m/%d/')),
                ('conversion_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('rows_processed', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='excel_processor.uploadedfile')),
            ],
            options={
                'verbose_name_plural': 'Conversion histories',
                'ordering': ['-conversion_timestamp'],
            },
        ),
    ]
