# Generated by Django 6.0.1 on 2026-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_conversionhistory_client_id_uploadedfile_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionhistory',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='conversionhistory',
            name='output_csv_path',
            field=models.FileField(upload_to='outputs/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
